#server_names = ['dnswarden-doh2-ipv6','cloudflare-ipv6','gridns-jp-ipv6','jp.tiar.app-doh-ipv6'] 
server_names = ['cloudflare-family','cloudflare','dnslify-doh','jp.tiarap.org','powerdns-doh','doh-sg-blahdns']
#程序监听地址。如果要对所有地址服务，可以监听'0.0.0.0:53'或'[::]:53'.
#也可以监听多个地址，例如 listen_addresses = ['127.0.0.1:53', '192.168.1.2:53']
listen_addresses = ['127.0.0.1:5353']
max_clients = 250
# Use servers reachable over IPv4
ipv4_servers = true
# Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity
ipv6_servers = false
# Use servers implementing the DNSCrypt protocol
dnscrypt_servers = true
# Use servers implementing the DNS-over-HTTPS protocol
doh_servers = true
## Require servers defined by remote sources to satisfy specific properties
# Server must support DNS security extensions (DNSSEC)
#服务器支持DNSSEC
require_dnssec = false
# Server must not log user queries (declarative)
#服务器不会记录查询
require_nolog = true
# Server must not enforce its own blacklist (for parental control, ads blocking...)
#服务器不会过滤结果
require_nofilter = true
# Server names to avoid even if they match all criteria
#服务器黑名单
[query_log]
  file = '/var/log/dnscrypt-proxy/query.log'

[nx_log]
  file = '/var/log/dnscrypt-proxy/nx.log'

[sources]
  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
